Windows support (#78)
Add Windows builds for omniscidb and pyomniscidb

diff --git a/recipe/meta.yaml b/recipe/meta.yaml
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,7 +1,7 @@
 {% set version = "5.10.2" %}  # PEP 386
 {% set source_version = version %}
 {% set base_version = version %}
-{% set number = "1" %}
+{% set number = "2" %}
 {% set cuda_enabled = cuda_compiler_version is not undefined and cuda_compiler_version == '11.0' %}
 {% set build_ext_version = "1.0.0" %}
 {% set build_ext = "cuda" if cuda_enabled else "cpu" %}
@@ -24,6 +24,8 @@ package:
 source:
   url: https://github.com/omnisci/omniscidb/archive/v{{ source_version }}.tar.gz
   sha256: c800f768c52a06bc6c1f9140cae427becc3adea0bd3947b80cc703afdeef91b8
+  patches:
+    - 0002-Fix-Windows-build.patch  # [win]
 
 build:
   number: {{ number }}
@@ -33,7 +35,7 @@ outputs:
 
   - name: omniscidb-common
     version: {{ version }}
-    script: build-omniscidb.sh
+    script: build-omniscidb.sh  # [linux64]
     build:
       string: {{ build_string }}
       # cpu-only omniscidb-common for cuda is required only for
@@ -125,10 +127,13 @@ outputs:
 
   - name: omniscidb
     version: {{ version }}
-    script: build-omniscidb.sh
+    script: build-omniscidb.sh   # [linux64]
+    script: build-omniscidb.bat  # [win]
     build:
       string: {{ build_string_ext }}
-      skip: true  # [cuda_compiler_version not in (undefined, "None", "11.0") or not linux64]
+      skip: true  # [cuda_compiler_version not in (undefined, "None", "11.0")]
+      skip: true  # [osx]
+      skip: true  # [win and cuda_compiler_version != "None"]
       missing_dso_whitelist:
         - '*/libcuda.*'  # [cuda_compiler_version not in (undefined, "None")]
       track_features:
@@ -162,87 +167,94 @@ outputs:
         - maven
       host:
         - arrow-cpp ={{ arrow_version }}=*{{ build_ext }}
-        - bisonpp
+        - bisonpp  # [not win]
         - blosc
         - boost-cpp
         - clangdev {{ llvm_version }}
         - double-conversion
-        - flex
+        - flex  # [not win]
         - fmt
         - gflags
         - glog
         - llvmdev {{ llvm_version }}
         - llvm {{ llvm_version }}
         - libarchive
+        - libevent  # [win]
         - libgdal
         - libkml
         - libpng
         - librdkafka
-        - ncurses
-        - openldap
+        - ncurses   # [not win]
+        - openldap  # [not win]
         # Workaround https://github.com/mamba-org/boa/issues/119 :
         - openssl 1.1.1*
         - snappy
         - tbb
         - tbb-devel
         - thrift-cpp {{ thrift_version }}
+        - winflexbison  # [win]
       run:
         - arrow-cpp-proc {{ arrow_proc_version }} {{ build_ext }}
         - boost-cpp
         - bzip2
         # omnscidb Load-time UDF support calls clang++
-        - gxx_{{ target_platform }}
+        - gxx_{{ target_platform }}  # [not win]
         - libclang-cpp {{ llvm_version }}
-        - ncurses
+        - ncurses  # [not win]
         - openjdk 8.*
         - xz
         - zlib
-        - {{ pin_subpackage('omniscidb-common',  max_pin='x.x.x') }}
+        - {{ pin_subpackage('omniscidb-common',  max_pin='x.x.x') }}  # [not win]
       run_constrained:
         - arrow-cpp-proc {{ arrow_proc_version }} {{ build_ext }}
         - cudatoolkit >=11.0  # [cuda_compiler_version not in (undefined, "None")]
 
     test:
       commands:
-        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci_server
-        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci_initdb
-        - test -f ${PREFIX}/{{ install_base }}/bin/omnisql
-        - test -f ${PREFIX}/{{ install_base }}/bin/KafkaImporter
-        - test -f ${PREFIX}/{{ install_base }}/bin/StreamImporter
+        # binary
+        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci_server  # [unix]
+        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci_initdb  # [unix]
+        - test -f ${PREFIX}/{{ install_base }}/bin/omnisql         # [unix]
+        - test -f ${PREFIX}/{{ install_base }}/bin/KafkaImporter   # [unix]
+        - test -f ${PREFIX}/{{ install_base }}/bin/StreamImporter  # [unix]
+        - if not exist %PREFIX%\bin\omnisci_server.exe exit 1     # [win]
+        - if not exist %PREFIX%\bin\omnisci_initdb.exe exit 1     # [win]
+        - if not exist %PREFIX%\bin\omnisql.exe exit 1            # [win]
 
         # Verify the activation scripts are in-place.
         {% for state in ["activate", "deactivate"] %}
-        - test -f "${PREFIX}/etc/conda/{{ state }}.d/{{ PKG_NAME }}_{{ state }}.sh"
+        - test -f "${PREFIX}/etc/conda/{{ state }}.d/{{ PKG_NAME }}_{{ state }}.sh"  # [unix]
         {% endfor %}
         # Try using the activation scripts.
         - |
-          if [[ -x "$(command -v omnisql)" ]]
-          then
-            echo "Found omnisql in PATH"
-          else
-            echo "omnisql not found in PATH(=$PATH)" && exit 1
-          fi
-          source ${PREFIX}/etc/conda/deactivate.d/{{ PKG_NAME }}_deactivate.sh
-          if [[ -x "$(command -v omnisql)" ]]
-          then
-            echo "Unexpectedly found omnisql in PATH(=$PATH) after deactivation"  && exit 1
-          else
-            echo "omnisql not in PATH after deactivation"
-          fi
-          source ${PREFIX}/etc/conda/activate.d/{{ PKG_NAME }}_activate.sh
+          if [[ -x "$(command -v omnisql)" ]]                                                 # [unix]
+          then                                                                                # [unix]
+            echo "Found omnisql in PATH"                                                      # [unix]
+          else                                                                                # [unix]
+            echo "omnisql not found in PATH(=$PATH)" && exit 1                                # [unix]
+          fi                                                                                  # [unix]
+          source ${PREFIX}/etc/conda/deactivate.d/{{ PKG_NAME }}_deactivate.sh                # [unix]
+          if [[ -x "$(command -v omnisql)" ]]                                                 # [unix]
+          then                                                                                # [unix]
+            echo "Unexpectedly found omnisql in PATH(=$PATH) after deactivation"  && exit 1   # [unix]
+          else                                                                                # [unix]
+            echo "omnisql not in PATH after deactivation"                                     # [unix]
+          fi                                                                                  # [unix]
+          source ${PREFIX}/etc/conda/activate.d/{{ PKG_NAME }}_activate.sh                    # [unix]
         # Test installation
-        - omnisql -v
-        - which omnisci_initdb
-        - which omnisci_server
+        - omnisql -v              # [unix]
+        - which omnisci_initdb    # [unix]
+        - which omnisci_server    # [unix]
+        - omnisql.exe -v          # [win]
         - |
-          if [ -x "$(command -v nvidia-smi)" ]; then  # [cuda_compiler_version not in (undefined, "None")]
-            mkdir data && omnisci_initdb data
-            omnisci_server --version
-            rm -rf data
-          fi                                          # [cuda_compiler_version not in (undefined, "None")]
+          if [ -x "$(command -v nvidia-smi)" ]; then  # [unix and cuda_compiler_version not in (undefined, "None")]
+            mkdir data && omnisci_initdb data         # [unix and cuda_compiler_version not in (undefined, "None")]
+            omnisci_server --version                  # [unix and cuda_compiler_version not in (undefined, "None")]
+            rm -rf data                               # [unix and cuda_compiler_version not in (undefined, "None")]
+          fi                                          # [unix and cuda_compiler_version not in (undefined, "None")]
         # these are provided by omniscidb-common package:
-        - which omnisci_insert_sample_data
-        - which startomnisci
+        - which omnisci_insert_sample_data  # [unix]
+        - which startomnisci  # [unix]
 
     about:
       home: https://www.omnisci.com/
@@ -262,7 +274,8 @@ outputs:
 
   - name: pyomniscidb
     version: {{ version }}
-    script: build-pyomniscidb.sh
+    script: build-pyomniscidb.sh   # [linux64]
+    script: build-pyomniscidb.bat  # [win]
     build:
       skip: true  # [cuda_compiler_version in ("11.0",)]
       string: {{ py_build_string }}
@@ -519,6 +532,7 @@ about:
 
 extra:
   recipe-maintainers:
+    - guilhermeleobas
     - xmnlab
     - pearu
     - andrewseidl
